Esta sesión servirá para introducir a los estudiantes a Python (de modo breve), así como a las librerias de NumPy y Matplotlib, que serán de las mas utilizadas todo el curso.

# Básico de Python

## Variables

In [1]:
# Creación de variables y tipos
texto = 'Hola mundo'
enteros = 2
flotantes = 1.34
booleanos = True

In [2]:
print(texto)
print(enteros)
print(flotantes)
print(booleanos)

Hola mundo
2
1.34
True


**Importante:** Los nombres de las variables son sensibles a mayúsuculas, deben comenzar con una letra de la A a la Z o guión bajo (_) y no pueden ser llamadas igual a las palabras reservadas.

In [3]:
# Ejemplos de sensibilidad a las mayúsculas
Texto = 'Esta variable inicia con una mayúscula'
texto = 'Esta variable no'
TexTO = 'Esta variable tiene mayúsculas al final'

print(texto)

Esta variable no


In [4]:
# Palabras reservadas (no pueden utilizarse para creación de variables)
import keyword

print(', '.join(keyword.kwlist))

False, None, True, and, as, assert, async, await, break, class, continue, def, del, elif, else, except, finally, for, from, global, if, import, in, is, lambda, nonlocal, not, or, pass, raise, return, try, while, with, yield


Algunos errores que podemos encontrar

In [5]:
# Ejemplos de nombres inválidos
# No inician con letras o guion bajo
3var = 3 
.var = 3

SyntaxError: ignored

In [6]:
# No pueden usarse palabras reservadas
async = 3

SyntaxError: ignored

# Cadenas

¿Comillas dobles o sencillas para crear cadenas? Ambas

In [7]:
cadena1 = 'algo'
cadena2 = "algo"

In [8]:
print(cadena1)
print(cadena2)

algo
algo


Podemos sumar y multiplicar cadenas

In [9]:
cadena3 = "alguna cosa"
print(cadena1 + cadena3)
print(cadena3*3)

algoalguna cosa
alguna cosaalguna cosaalguna cosa


Cambios para cadenas de caracteres

In [10]:
texto.lower()

'esta variable no'

In [11]:
texto.upper()

'ESTA VARIABLE NO'

In [12]:
texto.title()

'Esta Variable No'

Podemos separar nuestra cadena dado un patrón

In [13]:
texto = 'Esta, cadena, la, separaré, por, comas'
texto.split(', ')

['Esta', 'cadena', 'la', 'separaré', 'por', 'comas']

In [14]:
print(texto)
# Funcion muy importante
print(texto.replace('a', 'Z'))

Esta, cadena, la, separaré, por, comas
EstZ, cZdenZ, lZ, sepZrZré, por, comZs


## Operaciones con variables numéricas


In [15]:
# Defino mis variables
a = 5
b = 2

In [16]:
# Suma
print(f'Suma: {a + b}')
# Resta
print(f'Resta: {a - b}')
#Multiplicación
print(f'Multiplicación: {a * b}')
# División
print(f'División: {a / b}')
# Parte entera de la división
print(f'Parte entera de división: {a // b}')
# División modular
print(f'Residuo: {a % b}')

Suma: 7
Resta: 3
Multiplicación: 10
División: 2.5
Parte entera de división: 2
Residuo: 1


## Listas

In [17]:
tiempos_traslado = [3, 34, 23, 12, 3, 4]
tiempos_traslado

[3, 34, 23, 12, 3, 4]

In [18]:
lista_mixta = ["Juan", 23, 54, 23, False, 'Avión']
lista_mixta

['Juan', 23, 54, 23, False, 'Avión']

In [21]:
range(10)

range

In [22]:
sucesion = list(range(10))
sucesion

list

Podemos localizar elementos de las listas con sus índices (Slicing)

In [26]:
lista_mixta[3]

23

In [27]:
lista_mixta[-1]

'Avión'

In [28]:
sucesion[1:4]

[1, 2, 3]

In [30]:
# Todos los pares considerando al cero
sucesion[::2]

[0, 2, 4, 6, 8]

In [31]:
print(lista_mixta)
lista_mixta.index('Avión')

['Juan', 23, 54, 23, False, 'Avión']


5

Concatenar listas


In [32]:
a = [1, 2, 3]
b = [4, 5, 6]

a + b

[1, 2, 3, 4, 5, 6]

Agregar (apendizar) elementos a una lista

In [33]:
listita = [1, 4, 5, 8]
listita.append(9)
listita

[1, 4, 5, 8, 9]

Ordenar listas

In [34]:
lista = [4,2,5,7,3,8]
lista.sort()
lista

[2, 3, 4, 5, 7, 8]

In [35]:
lista = [4,2,5,7,3,8]
lista.sort(reverse = True)
lista

[8, 7, 5, 4, 3, 2]

## Texto como lista de caracteres

In [36]:
print(texto)
texto[2]

Esta, cadena, la, separaré, por, comas


't'

## Conjuntos

In [37]:
{1, 2, 2, 3, 4}

{1, 2, 3, 4}

In [38]:
set(['a', 'b', 't', 'c', 't'])

{'a', 'b', 'c', 't'}

Funciones de transformacion

In [ ]:
list()
set()
int()
float()
str()
bool()

## Diccionarios (de los elementos mas importantes, posiblemente los utilicen mucho)

In [42]:
datos = {
    "nombre": "Manuel Pérez", 
    "carrera": 'Veterinaria', 
    "sueldo": 30000, 
    "es_casado": False, 
    "hijos": [
              {"nombre": "Juan Pérez", "edad": 5}, 
              {"nombre": "María Pérez", "edad": 3}
              ]
}


datos

{'carrera': 'Veterinaria',
 'es_casado': False,
 'hijos': [{'edad': 5, 'nombre': 'Juan Pérez'},
  {'edad': 3, 'nombre': 'María Pérez'}],
 'nombre': 'Manuel Pérez',
 'sueldo': 30000}

In [43]:
datos['es_casado']

False

In [44]:
datos['hijos']

[{'edad': 5, 'nombre': 'Juan Pérez'}, {'edad': 3, 'nombre': 'María Pérez'}]

In [45]:
# ¿Cuántos hijos tiene?
print(type(datos['hijos']))
len(datos['hijos'])

<class 'list'>


2

In [46]:
datos.keys()

dict_keys(['nombre', 'carrera', 'sueldo', 'es_casado', 'hijos'])

In [47]:
datos.values()

dict_values(['Manuel Pérez', 'Veterinaria', 30000, False, [{'nombre': 'Juan Pérez', 'edad': 5}, {'nombre': 'María Pérez', 'edad': 3}]])

In [48]:
contactos = [
             {
                 "nombre": "A", 
                "telefono": 2121
             }, {
                 "nombre": "B", 
                 "email": 'email@asdf.c'
             }
]

In [49]:
len(contactos)

2

## Booleanos (Verdadero o Falso, para verificaciones)

In [50]:
mi_primer_booleano = False
mi_primer_booleano

False

In [51]:
# Revisar si valores son iguales
3 == 4

False

In [52]:
cadena = 'El cazo'
cadena == 'sarten'

False

In [53]:
cadena == 'El cazo'

True

In [54]:
cadena == 'el cazo'

False

In [55]:
n = 3

In [56]:
print(n)

3


In [58]:
# Un número es mayor a otros
print(n > 3)
print(n <= 3)
print(n == 3) 

False
True
True


In [59]:
type('asdfas') is str

True

In [61]:
not 3 > 3

True

In [63]:
# Revisa si un elemento no está en la lista
10 not in sucesion

False

Comparando **float** con **int**:

In [64]:
m = 2
n = 2.0

print(type(m))
print(type(n))

<class 'int'>
<class 'float'>


In [65]:
# ¿Cual será el valor de esta comparación?
m == n

True

¿Y con comillas y dobles comillas?

In [66]:
'algo' == "algo"

True

# Estructuras de control

## Condicionales "If", "Elif" y "Else"

In [68]:
n = 'asd'
if type(n) is int:
    print('n es un entero')
    print('Esta otra linea')
    print('Una más')
else:
    print('n no es entero')

n no es entero


In [72]:
n = 89
if n == 7:
    print("n es 7")
elif n > 90:
    print('n es mayor a 90')
elif n < 2:
    print("n es menor a 2")
else:
    print('ninguna de las condiciones anteriores se cumplió')

ninguna de las condiciones anteriores se cumplió


### While

El while se ejecuta hasta que se cumple una condición.

Es importante notar que el ciclo **puede ejecutarse infinitamente** si la condición nunca se cumple.

In [73]:
i = 0
while i < 10:
    i += 1 # i = i + 1
    print(i)

1
2
3
4
5
6
7
8
9
10


In [74]:
# Secuencia de fibonacci
a, b = 0, 1          

secuencia = []

while a < 1000:     
  secuencia.append(a)
  a, b = b, a + b

secuencia

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]

### For

Ejecuta el ciclo para cada elemento en un iterable



In [75]:
for i in range(10):
    print(i + 2)

2
3
4
5
6
7
8
9
10
11


In [76]:
lista = ['Juan', 'María', 'Max', 'Alfonso']

Listas por comprension

In [77]:
print(lista)

# crea sólo una copia de la lista
nueva_lista = [x + ' comió algo' for x in lista]
nueva_lista

['Juan', 'María', 'Max', 'Alfonso']


['Juan comió algo', 'María comió algo', 'Max comió algo', 'Alfonso comió algo']

In [78]:
import math

In [79]:
promedios = [5.9, 6.7, 8.2, 10, 3, 0]
[math.ceil(calificacion) if calificacion > 6 and calificacion % 1 > .3 else math.floor(calificacion) for calificacion in promedios]

[5, 7, 8, 10, 3, 0]

In [ ]:
# El código anterior equivale a lo siguiente
nuevos_promedios = []
for x in promedios:
    if x > 6 and x % 1 > .3:
        nuevos_promedios.append(math.ceil(x))
    else:
        nuevos_promedios.append(math.floor(x))
nuevos_promedios

## Control de ciclos

In [80]:
j = 1
while True:
    j *= 10 # j = j*10
    print(j)
    if j > 100:
        break

10
100
1000


In [81]:
for j in range(10):
    if 4 < j < 7:
        print(f'omitiendo')
        continue
    print(j)

0
1
2
3
4
omitiendo
omitiendo
7
8
9


## List Comprehension (Creando listas por comprensión)

In [ ]:
print(lista)

In [ ]:
# crea sólo una copia de la lista
nueva_lista = [x + 5 for x in lista]
nueva_lista

# NumPy (libreria para operaciones matemáticas)

## Creación de Arrays (arreglos)

In [82]:
import numpy as np

In [83]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
vista = arr[:3]
vista

array([0, 1, 2])

In [86]:
vista[:] = 0
vista

array([0, 0, 0])

In [87]:
copia = arr[:5].copy()
copia

array([0, 0, 0, 3, 4])

In [88]:
x = np.array([1,3,2,2,5,5,5])

In [89]:
# Suma de los elementos de x
np.sum(x)

23

In [90]:
# Media
np.mean(x)

3.2857142857142856

In [91]:
# Mediana
np.median(x)

3.0

In [92]:
# Varianza
np.var(x)

2.4897959183673466

In [93]:
# Desviación estándar
np.std(x)

1.577908716741037

In [94]:
my_array = np.array([1, 3, 4])

In [95]:
my_array

array([1, 3, 4])

In [97]:
my_array + my_array

array([2, 6, 8])

## Arreglos 2-dimensionales (matrices)

In [98]:
my_matrix = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
my_matrix

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
my_array[1]

3

In [102]:
my_matrix.reshape((3, 4))

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
my_matrix.shape

(4, 3)

In [103]:
# Crear arreglos de ceros
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
img_ex = np.zeros((3, 5, 5))
print(type(img_ex))
img_ex

In [ ]:
# Creación de números aleatorios
np.random.randint(0, 100, (5, 5))

In [ ]:
np.random.seed(10)

In [ ]:
A = np.random.randint(0, 100, (5, 5))
A

In [ ]:
# producto punto
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

np.dot(x, y)

In [ ]:
# Producto de matrices
A = np.random.randint(0, 2, (3, 2))
B = np.random.randint(0, 2, (2, 3))


In [ ]:
print(A)
print(B)

In [ ]:
Multiplicacion = np.dot(A,B)
Multiplicacion

In [ ]:
otra = np.dot(B,A)
otra

In [ ]:
# invertir matriz
C = np.array([[2,1],[1,0]])

Ainv = np.linalg.inv(C)
Ainv

# Funciones

Para definir las funciones seguimos la sintaxis

```python
def <nombre de la funcion>((parametros)):
    <bloque de codigo>
    (opcional) return <valor a regresar>
```

El nombre de la función sigue las mismas reglas que el nombre de las variables.

Para regresar un valor de nuestra función existen dos palabras reservada ```return``` y ```yield```. La primera termina la ejecución de la función cuando la encuentra y puede estar en cualquier parte de esta, incluso puede haber varios returns en distintas partes de la función. La segunda, ```yield``` convierte a la función en un iterable. A grandes rasgos, lo que hace es pausar la ejecución de la función hasta que se le pida el siguiente valor.

In [ ]:
def hola(nombre):
    print(f'Hola {nombre}')

In [ ]:
hola('Javier')

In [ ]:
# No existe el polimorfismo
def hola(nombre, param):
    print(nombre*param)

In [ ]:
hola('Javier')

In [ ]:
def hola2(nombre, saludo =  'Hola'):
    print(f'{saludo} {nombre}')

In [ ]:
hola2('Javier', 'Que onda')

In [ ]:
def imprime_numeros(n = 10, para = None):
    for i in range(n):
        if i == para:
            return 'nos detuvimos'
        print(i)
    
    return 'terminamos'


In [ ]:
imprime_numeros(20)

In [ ]:
# Recursividad
def factorial(n):
    if n == 0:
        return 1
    return n*factorial(n-1)

In [ ]:
factorial(3)

## Visualización de datos

Para visualizar datos podemos ocupar el módulo ```matplotlib```. Cabe notar que no es el único módulo para gráficar, pero sí el más fácil de usar. Otro módulo muy usado es [```plotly```](https://plotly.com/python/) que puede crear gráficos interactivos

In [ ]:
import matplotlib.pyplot as plt
np.random.seed(15)

## Histograma

In [ ]:
datos = np.random.normal(size = 400)
datos

In [ ]:
plt.hist(datos)

## Gráfica de dispersión

In [ ]:
# Generamos 200 números aleatorios de 0 a 1, los escalamos para que lleguen de 0 a 10 y luego los trasladamos para que queden entre -5 y 5
x = np.random.rand(200) * 10 - 5
# Hacemos que y igual a x al cubo y agregamos algo de ruido blanco gaussiano
y = x**3 + np.random.normal(0, 20, 200)

plt.scatter(x, y)

In [ ]:
x

In [ ]:
# Se ocupa la variable y para asignale color a los datos
plt.scatter(x, y, c = y)

In [ ]:
# Se elige otra paleta de colores
plt.scatter(x, y, c = y, cmap = 'plasma')

## Lineas

In [ ]:
# Generamos datos
x = np.linspace(0, 10, 100)
y = x + 1/3*np.sin(x * 2) - np.cos(x) - 1/7 * np.sin(np.sqrt(x)) + np.random.normal(0, 2, 100)

plt.figure(figsize=(10, 5))
plt.plot(x, y)
plt.title('Gráfica con datos simulados')
plt.xlabel('Tiempo')
plt.ylabel('Precio')


In [ ]:
y

# Ejercicios

## 1. Crear un condicional que imprima si un número es par o impar

Definir una variable con un número antes del if

**Pista**: un número es par si módulo 2 es igual a cero

In [ ]:
print(3 % 2)
4 % 2

## 2. Crear un ciclo que imprima todos los números de 1 a n

definir n como variable y utilizarla para el ciclo

## 3. Crear un ciclo que imprima todos los números pares del uno al n

## 4. Crear un ciclo que imprima todos los números impares de 5 a n para n > 5

Revisar que n sea mayor a 5 antes de entrar al ciclo, si no lo es, imprimir "n debe ser mayor a 5"

## 5. Con un ciclo, crear la siguiente lista: 1, 4, 9, 16, 25, 36 con el método ".append()"

## 6. Hacer el ejercicio anterior con list comprehension

## 7. Imprimir, linea por linea, el siguiente patrón 3 veces con un ciclo y el operador módulo

a \\
aa \\
aaa \\
aaaa \\
a \\
aa \\
aaa \\
aaaa \\


**Pista**: Ocupar la siguiente propiedad de las cadenas

In [ ]:
"a" * 5 

## 8. Crear una lista sólo con los elementos mayores a n de la siguiente lista.

1, 34, 2, 4, 6, 8, 5, 7, 345, 23

Con n una variable

```python
n = 23

<bloque del codigo>
```

## 9. Crear un ciclo que imprima todos los múltiplos de m hasta n

E.g. para m = 2 y n = 6 la salida debería ser

2 \\
4 \\
6 \\
8 \\
10 \\
12

## 10. Ejercicios un poco más complicados

- https://www.codechef.com/problems/EID

[1, 2, 4, 56, 6, 5, 4, 56, 6]

la diferencia minima entre dos elementos distintos de la lista


- https://www.codechef.com/problems/CHEGLOVE

```python
listaA = [7, 2, 3] # Mano
listaB = [4, 5, 6] # Guante

len(listaA) == len(listaB) # True

# Si los elementos de a son menores a los elementos de b element-wise, entonces imprimir
print('Queda bien')
# Si no, "voltear el guante" y hacer la misma verificacion
print('Se volteo y todo bien')

# Si aun no queda bien
print('NO le quedo el guante')

```
- https://www.codechef.com/problems/SEGM01

```python
cadena = '000011100111'
# Si todos los 1's forman un bloque
print(True)
# Si no, i.e. hay un cero en medio
print(False)

```

- https://www.codechef.com/problems/HOWMANY

```python
n = 5454

<bloque de código>
>> 4
```

```python
str(n) #5454
```
- https://www.codechef.com/problems/SINS

```python
m = 11
b = 5

m, b
11, 5
6, 5
1, 5
1, 4
1, 3
1, 2
1, 1

# La salida del programa
print(m + b)
```

# 11. Creación de las siguientes funciones

 - Crear una función para calcular la media (promedio) de una lista




- Otra para la varianza

Los ejercicios 1, 2, 3, 7, 8, 9, convertirlos en funciones

# Ligas últiles

- [operadores](https://www.w3schools.com/python/python_operators.asp)
- [list comprehension](https://www.w3schools.com/python/python_lists_comprehension.asp)