[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]()

# Dependencias

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Solo para que al mostrarnos los arreglos no nos de los valores grandes en notación científica
np.set_printoptions(suppress=True)

# Carga de datos e interpretación


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Curso-NN-de-Cero/semana2/pruebas_datos.csv')

In [ ]:
df

OTR       OCR  min_time_two_events  mean_time_two_events  \
0     -0.264140 -0.171596            -0.034334              0.173848   
1     -0.267371  0.071957            -0.034334             -0.394632   
2     -0.268571  0.392193            -0.034334             -0.596358   
3     -0.267320 -0.082373            -0.034334             -0.337735   
4     -0.268375  0.094866            -0.034334             -0.551568   
...         ...       ...                  ...                   ...   
50577 -0.270438  0.040609            -0.034334             -0.587633   
50578 -0.269299  0.040609            -0.034334             -0.704571   
50579 -0.270456  0.952123            -0.034334             -0.592510   
50580 -0.270274  2.659404            -0.034334             -0.648742   
50581 -0.270277  0.662754            -0.034334             -0.694323   

       10_p_time_two_events  med_time_two_events  25_p_time_two_events  \
0                 -0.051861            -0.194635             -0.103174   
1                 -0.051861            -0.261262             -0.107967   
2                 -0.051861            -0.261262             -0.107967   
3                 -0.051861            -0.260286             -0.107966   
4                 -0.051861            -0.261262             -0.107967   
...                     ...                  ...                   ...   
50577             -0.051861            -0.261262             -0.107967   
50578             -0.051861            -0.261262             -0.107967   
50579             -0.051861            -0.261262             -0.107967   
50580             -0.051861            -0.261262             -0.107967   
50581             -0.051861            -0.261262             -0.107967   

       75_p_time_two_events  90_p_time_two_events  max_time_two_events  ...  \
0                 -0.493894              0.669772             0.113391  ...   
1                 -0.578826             -0.714095             0.478099  ...   
2                 -0.579091             -0.864277             0.449648  ...   
3                 -0.574153              0.401915            -0.240214  ...   
4                 -0.579396             -0.876131            -0.003950  ...   
...                     ...                   ...                  ...  ...   
50577             -0.579589             -0.811629            -0.928057  ...   
50578             -0.573424             -0.873859            -1.356834  ...   
50579             -0.579500             -0.894274             0.012924  ...   
50580             -0.579477             -0.886564            -0.241991  ...   
50581             -0.578331             -0.879211            -1.284239  ...   

       90_p_lifetime_cancel  max_lifetime_cancel  NbTradeVenueMic  \
0                  0.446317             0.159271        -0.989267   
1                  0.341803             0.053125        -0.989267   
2                 -0.843156            -0.601191        -0.989267   
3                  0.205183            -0.085628        -0.989267   
4                  0.447088             0.160054        -0.989267   
...                     ...                  ...              ...   
50577             -0.499086            -0.800893        -0.989267   
50578             -0.927494            -1.235990        -0.989267   
50579              0.464365             0.177600        -0.989267   
50580              0.203363            -0.087476        -0.989267   
50581             -0.921142            -1.229538        -0.989267   

       MaxNbTradesBySecond  MeanNbTradesBySecond  min_dt_TV1  mean_dt_TV1  \
0                -0.459192              0.414463   -0.068166     2.257305   
1                 0.065955              2.493944   -0.174906    -0.259542   
2                 0.223500              1.925729   -0.174906    -0.350248   
3                -0.406677              1.394323   -0.174906    -0.056171   
4                 0.170985              1.041917   -0.174906    -0.327099   
...               

In [ ]:
# Los valores 1 son NON-HFT y los 0 son HFT
df.type.value_counts()

0    30522
1    20060
Name: type, dtype: int64

## Agregando descripción a los datos

Los datos son públicos, fueron utilizados en una competencia que pueden consultar [AQUÍ](https://challengedata.ens.fr/participants/challenges/50/) (para poder ingresar necesitarán registrarse y luego copiar la dirección en su navegador). En esta competencia registraron muchas características de "traders", para tratar de clasificarlos en HFT (High Frequency Traders) o NON-HFT, esto porque es de gran interes tratar de estudiar el impacto que tienen los HFT en los mercados, ya que lo que hacen es realizar intercambios dando ordenes de intercambio a un mecanismo llamado Limit Order Book (LOB), al cual le ordenan realizar compras o ventas a precios que ellos deseen.

## Descripción de las variables
1. NbTradeVenueMic (23) : Número de centros de negociación en los que opera el jugador del mercado

De todos los centros de negociación, estadísticas sobre el número de operaciones observadas por segundo

2. MaxNbTradesBySecond (24)
3. MeanNbTradesBySecond (25) 

Estadísticas sobre el delta de tiempo observado entre dos operaciones en la plataforma de negociación TV_1[1]:

4. min_dt_TV1 (26)
5. med_dt_TV1 (28)
6. mean_dt_TV1 (27)

Estadísticas sobre el delta de tiempo observado entre dos operaciones que se producen en la plataforma de negociación TV_1 y luego en la plataforma de negociación TV_2:

7. min_dt_TV1_TV2 (29)
8. med_dt_TV1_TV2 (31)
9. mean_dt_TV1_TV2 (30)

Estadísticas sobre el delta de tiempo observado entre dos operaciones que se producen en la plataforma de negociación TV_1 y luego en la plataforma de negociación TV_3:

10. min_dt_TV1_TV3 (32)
11. med_dt_TV1_TV3 (34)
12. mean_dt_TV1_TV3 (33)

Estadísticas sobre el delta de tiempo observado entre dos operaciones que se producen en la plataforma de negociación TV_1 y luego en la plataforma de negociación TV_4 :

13. min_dt_TV1_TV4 (35)
14. med_dt_TV1_TV4 (37)
15. mean_dt_TV1_TV4(36)

De todos los centros de negociación, número de segundos durante el día de negociación donde se observa al menos una operación del jugador del mercado i

16. NbSecondWithAtLeatOneTrade(38)

En la plataforma de negociación TV_1, tres proporciones entre el número de todo tipo de eventos[2] enviados a la LOB y:

17. el número de operaciones (OTR) (4)
18. el número de eventos de tipo cancelación (OCR) (5)
19. el número de eventos de tipo de modificación (OMR) (6)

En el centro de negociación TV_1, estadísticas durante el delta de tiempo observado entre dos eventos de todo tipo enviados:

20. min_time_two_events (7)
21. mean_time_two_events (8)
22. 10_p_time_two_events (9)
23. med_time_two_events (10)
24. 25_p_time_two_events (11)
25. 75_p_time_two_events (12)
26. 90_p_time_two_events (13)
27. max_time_two_events (14)

En la plataforma de negociación TV_1, estadísticas a lo largo de la vida útil observada de las órdenes canceladas:

28. min_lifetime_cancel (15)
29. mean_lifetime_cancel (16)
30. 10_p_lifetime_cancel (17)
31. med_lifetime_cancel (18)
32. 25_p_lifetime_cancel (19)
33. 75_p_lifetime_cancel (20)
34. 90_p_lifetime_cancel (21)
35. max_lifetime_cancel (22)

Extra variables

36. Type: HF, Non HFT (39)
37. Day
38. Share
39. Trader
40. Index


In [ ]:
df.shape

(50582, 26)

In [ ]:
X_prob = np.array(df.drop(['type'], axis=1))
X_prob

array([[-0.26413997, -0.17159563, -0.03433358, ...,  2.25730527,
         0.21564981, -0.43020348],
       [-0.26737141,  0.07195718, -0.03433358, ..., -0.25954205,
        -0.25743172, -0.41553282],
       [-0.26857105,  0.39219296, -0.03433358, ..., -0.35024783,
        -0.25743176, -0.35151541],
       ...,
       [-0.27045626,  0.9521233 , -0.03433358, ..., -0.07680184,
        -0.25668942, -0.41419912],
       [-0.27027382,  2.65940442, -0.03433358, ..., -0.27547952,
        -0.25713323, -0.3888589 ],
       [-0.2702773 ,  0.66275362, -0.03433358, ...,  0.28933079,
        -0.25311955, -0.423535  ]])

In [ ]:
X_prob.shape

(50582, 25)

In [ ]:
Y_prob = np.array(df['type'])
Y_prob

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
num_inputs = 25
num_outputs = 2

W = np.random.normal(0, 0.1, (num_inputs, num_outputs)) # Jugaremos con este parametro
b = np.zeros(num_outputs) # Jugaremos con este parametro

In [ ]:
print(W)
print(b)

[[-0.01694981 -0.0966736 ]
 [-0.03505579 -0.05736402]
 [ 0.15552063  0.0590558 ]
 [ 0.04666783 -0.08390879]
 [ 0.04048615  0.24244281]
 [-0.04751952 -0.10583661]
 [-0.04693932  0.11031664]
 [-0.17467619  0.12365899]
 [ 0.06472148  0.12595984]
 [ 0.08409324 -0.13724014]
 [ 0.01159163  0.04478774]
 [ 0.10107029 -0.08785719]
 [-0.15619782 -0.01404767]
 [-0.05405491 -0.00847797]
 [ 0.21349789 -0.1927344 ]
 [ 0.18793461 -0.04464623]
 [ 0.02747125  0.07139376]
 [ 0.02692481 -0.21721912]
 [-0.05446717 -0.09680938]
 [ 0.20075386 -0.00773181]
 [ 0.09479823  0.00325012]
 [-0.09662318 -0.08834096]
 [ 0.02633828 -0.01731532]
 [ 0.04684183  0.03813998]
 [-0.11030633  0.03523526]]
[0. 0.]


# Definición de la operación SoftMax

Primero, notemos que dado un arreglo de numpy, nosotros podemos relizar sumas de diferentes formas utilizando el método "sum()". Al daro distintos argumentos se reliza de distintos modos.

Si no pasamos ningún parámetro a "sum()", lo que obtendremos será la suma de todas las entradas de nuestra matriz (o arreglo o tensor). 

Si damos como parámetro el "0", lo que nos regresará será la suma por columnas (es decir, en el eje 0)

Si damos como parámetro el "1", nos regresará la suma por filas (es decir, en el eje 1)

In [ ]:
X = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
X.sum(keepdims=True), X.sum(0, keepdims=True), X.sum(1, keepdims=True)

(array([[21.]]), array([[5., 7., 9.]]), array([[ 6.],
        [15.]]))

In [ ]:
X

array([[1., 2., 3.],
       [4., 5., 6.]])

Con esto podemos implementar de modo muy sencillo la función SoftMax, que consiste de 3 pasos:

1. Obtener el exponenete de cda uno de nuestros elementos.
2. Tomamos la suma de los elementos de su fila
3. Dividimos cada fila por su constante de normalización (sería una suma de exponenciales)

La expresión matemática de la función SoftMax es la siguiente:


$$ \mathrm{softmax}(\mathbf{X})_{ij} = \frac{\exp(\mathbf{X}_{ij})}{\sum_k \exp(\mathbf{X}_{ik})}. $$

In [ ]:
def softmax(X):
    X_exp = np.exp(X)
    partition = X_exp.sum(1, keepdims=True)
    return X_exp / partition

Veamos un ejemplo con la matriz de 2X3 creada anteriormente.

In [ ]:
softmax(X)

array([[0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096]])

Si observan con cuidado, pueden ver que con esta operación estamos transformando todas nuestras entradas en números positivos. Mas aún, cada fila suma 1, es decir, la convertimos en una distribución de probabilidad.

In [ ]:
x = np.random.normal(0, 1, (2, 5))
x_prob = softmax(x)
x_prob, x_prob.sum(1)

(array([[0.29315303, 0.25617589, 0.31410756, 0.07940121, 0.0571623 ],
        [0.05052356, 0.46004637, 0.13034993, 0.17365581, 0.18542433]]),
 array([1., 1.]))

# Definiendo el modelo

Aquí pueden ver que tipo de modelo vamos a implementar. En este caso es una regresión softmax.

In [ ]:
def net(X):
    return softmax(np.dot(X.reshape((-1, W.shape[0])), W) + b)

1. Comparado con el modelo de regresión lineal de la clase pasada ¿que notan?

2. ¿Que nos dará como salida ésta operación?

3. ¿Porqué?

# Definiendo la función de perdida

Usaremos la función Cross-Entropy, una de las mas populares dado que es buena para problemas de clasficación y en la actualidad, en machine learning son mas los problemas de clasificación que los de regresión.

La función es la siguiente:
$$ -\sum_{c=1}^My_{o,c}\log(p_{o,c}), $$

donde $M$ es la cantidad de clases que tenemos, $log$ la función de logaritmo natural, $y$ es $0$ o $1$ dependiendo de la etiqueta real de la clase $c$ y por último $p_{o,c}$ es la probabilidad predicha de que la observación $o$ pertenezca a la clase $c$.

Para calcular esto, en lugar de utilizar un ciclo "for" (que a veces termina siendo menos optimizado), utilizaremos funciones de numpy.

In [ ]:
# El resultado final es lo que alimentará a la cross-entropy, es decir etiqueta 
# de que pertenece a la clase 1 por la probabilidad de pertenecer a la clase 1
y = np.array([0, 2])
y_hat = np.array([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]

array([0.1, 0.5])

In [ ]:
def cross_entropy(y_hat, y):
    return - np.log(y_hat[range(len(y_hat)), y])

cross_entropy(y_hat, y)

array([2.30258509, 0.69314718])

# Precisión de la clasificación

En un problema de clasificación multi-clase, es decir, un problema en el que observemos varias caracteristicas de un elemento y decidamos a que clase pertenece dicho elemento. 

Por ejemplo: Un algoritmo de clasificación de imagenes que intente saber si algo es un perro, un gato o un ratón. Si introdujeramos características y al final diera un vector $(0.2, 0.38, 0.42)$, el algoritmo lo clasificaría como un ratón (lo marcaría como perteneciente a la tercer clase)

Cuando las predicciones son consistentes con las etiquetas verdaderas, decimos que son correctas. La presición de la clasificación son la cantidad de predicciones correctas entre todas las predicciones. Sin embargo, es muy difícil optimizar esto directamente (no es una función diferenciable), pero será muy importante para ver el rendimiento de nuestro modelo.

Lo que hacemos para ver la precisión es encontrar el valor mas grande en el vector de probabilidades, convertirlo en entero (porque muy probablemente sea un valor entr 0 y 1) y compararlo con las etiquetas verdaderas de nuestros datos.

In [ ]:
# ARGMAX regresa la posicion del elemento con mayor valor
np.array([[0.2,0.38, 0.42]]).argmax(axis=1)

array([2])

In [ ]:
def accuracy(y_hat, y):
    """Compute the number of correct predictions."""
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = y_hat.argmax(axis=1)
    cmp = y_hat.astype(y.dtype) == y
    return float(cmp.astype(y.dtype).sum())

In [ ]:
accuracy(y_hat, y) / len(y)

0.5

## Veamos como sería el accuracy para nuestro modelo con nuestros datos al azar

In [ ]:
X_prob

array([[-0.26413997, -0.17159563, -0.03433358, ...,  2.25730527,
         0.21564981, -0.43020348],
       [-0.26737141,  0.07195718, -0.03433358, ..., -0.25954205,
        -0.25743172, -0.41553282],
       [-0.26857105,  0.39219296, -0.03433358, ..., -0.35024783,
        -0.25743176, -0.35151541],
       ...,
       [-0.27045626,  0.9521233 , -0.03433358, ..., -0.07680184,
        -0.25668942, -0.41419912],
       [-0.27027382,  2.65940442, -0.03433358, ..., -0.27547952,
        -0.25713323, -0.3888589 ],
       [-0.2702773 ,  0.66275362, -0.03433358, ...,  0.28933079,
        -0.25311955, -0.423535  ]])

In [ ]:
accuracy(net(X_prob),Y_prob) / len(Y_prob)

0.7068917796844727

In [ ]:
W = np.random.normal(0, 0.1, (num_inputs, num_outputs)) # Jugaremos con este parametro
b = np.zeros(num_outputs) # Jugaremos con este parametro

In [ ]:
# Las probabilidades que predecimos para cada fila de nuestros datos
net(X_prob)

array([[0.57800654, 0.42199346],
       [0.52162556, 0.47837444],
       [0.47930976, 0.52069024],
       ...,
       [0.20482948, 0.79517052],
       [0.23477996, 0.76522004],
       [0.50205475, 0.49794525]])

In [ ]:
# La etiqueta verdadera de nuestros datos
Y_prob

array([1, 1, 1, ..., 1, 1, 1])